### ISSUE TITLE
Not working with latest PyCharm 2025.2.0.1

### ISSUE THREAD

**Issue by Eraldo** [strawberry-graphql/strawberry-pycharm-plugin#12]
## Describe the Bug

PyCharm throws errors by the second and suggests disabling the plugin.

Example trace:
```
Unhandled exception in [Kernel@i8ku5b7ot1jmdp1puptq, Rete(abortOnError=false, commands=capacity=2147483647,data=[onReceive], reteState=kotlinx.coroutines.flow.StateFlowImpl@59e5ddf, dbSource=ReteDbSource(reteState=kotlinx.coroutines.flow.StateFlowImpl@59e5ddf)), DbSourceContextElement(kernel Kernel@i8ku5b7ot1jmdp1puptq), ComponentManager(ApplicationImpl@2145353539), com.intellij.codeWithMe.ClientIdContextElementPrecursor@55e5b429, CoroutineName(FileBasedIndex Vfs Event Processor), Dispatchers.IO.limitedParallelism(1)]

java.lang.NoSuchMethodError: 'com.jetbrains.python.psi.PyNoneLiteralExpression com.jetbrains.python.psi.PyElementGenerator.createEllipsis()'
	at rocks.strawberry.StrawberryParametersProvider.getDecoratorAndTypeAndParameters(StrawberryParametersProvider.kt:19)
	at com.jetbrains.python.codeInsight.PyDataclassesKt.decoratorAndTypeAndMarkedCallee(PyDataclasses.kt:192)
	at com.jetbrains.python.codeInsight.PyDataclassesKt.parseDataclassParametersFromAST(PyDataclasses.kt:243)
	at com.jetbrains.python.codeInsight.PyDataclassesKt.parseDataclassParametersForStub(PyDataclasses.kt:167)
	at com.jetbrains.python.psi.impl.stubs.PyDataclassStubImpl$Companion.create(PyDataclassStubs.kt:54)
	at com.jetbrains.python.psi.impl.stubs.PyDataclassStubType.createStub(PyDataclassStubs.kt:17)
	at com.jetbrains.python.psi.impl.stubs.PyDataclassStubType.createStub(PyDataclassStubs.kt:14)
	at com.jetbrains.python.psi.impl.stubs.PyCustomizableStubElementType.createCustomStub(PyCustomizableStubElementType.java:21)
	at com.jetbrains.python.psi.impl.stubs.PyClassElementType.createStub(PyClassElementType.java:63)
	at com.jetbrains.python.psi.impl.stubs.PyClassElementType.createStub(PyClassElementType.java:29)
	at com.intellij.psi.stubs.StubElementFactoryAdapter.createStub(CoreStubElementRegistryServiceImpl.kt:67)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.createStub(DefaultStubBuilder.java:87)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.visitNode(DefaultStubBuilder.java:58)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.buildStubTree(DefaultStubBuilder.java:53)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:31)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:22)
	at com.intellij.psi.stubs.StubTreeBuilder.lambda$buildStubTree$1(StubTreeBuilder.java:143)
	at com.intellij.psi.stubs.StubTreeBuilder.handleStubBuilderException(StubTreeBuilder.java:98)
	at com.intellij.psi.stubs.StubTreeBuilder.lambda$buildStubTree$3(StubTreeBuilder.java:143)
	at com.intellij.psi.impl.PsiManagerImpl.runInBatchFilesMode(PsiManagerImpl.java:508)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:132)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:91)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.preciseCheck(PerFileElementTypeStubModificationTracker.java:228)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.lambda$endUpdatesBatch$3(PerFileElementTypeStubModificationTracker.java:136)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:54)
	at com.intellij.openapi.application.impl.AppImplKt$rethrowCheckedExceptions$2.invoke(appImpl.kt:106)
	at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.runReadAction(NestedLocksThreadingSupport.kt:784)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:1043)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:66)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.endUpdatesBatch(PerFileElementTypeStubModificationTracker.java:127)
	at com.intellij.util.indexing.events.ChangedFilesCollector$4.endBatch(ChangedFilesCollector.java:227)
	at com.intellij.util.indexing.events.ChangedFilesCollector$5.lambda$endBatch$2(ChangedFilesCollector.java:264)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:295)
	at com.intellij.util.indexing.events.ChangedFilesCollector$5.endBatch(ChangedFilesCollector.java:263)
	at com.intellij.util.indexing.events.VfsEventsMerger.processChanges(VfsEventsMerger.java:131)
	at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesInReadAction(ChangedFilesCollector.java:246)
	at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesToUpdateInReadAction(ChangedFilesCollector.java:194)
	at com.intellij.util.indexing.events.ChangedFilesCollector.lambda$processFilesInReadActionWithYieldingToWriteAction$3(ChangedFilesCollector.java:300)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:876)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:908)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:636)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:599)
	at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.tryRunReadAction(NestedLocksThreadingSupport.kt:826)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1221)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:95)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:152)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:140)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:229)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:681)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:756)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:712)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:680)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:209)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:95)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:599)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.executeSynchronously(NonBlockingReadActionImpl.java:523)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.executeSynchronously(NonBlockingReadActionImpl.java:226)
	at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesInReadActionWithYieldingToWriteAction(ChangedFilesCollector.java:302)
	at com.intellij.util.indexing.events.ChangedFilesCollector.lambda$ensureUpToDateAsync$2(ChangedFilesCollector.java:172)
	at com.intellij.util.concurrency.CoroutineDispatcherBackedExecutor$execute$1.invokeSuspend(executor.kt:89)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:613)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:1183)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:778)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:765)
	Suppressed: com.intellij.util.ExceptionUtilRt$RethrownStack: Rethrown at
		at com.intellij.util.ExceptionUtilRt.addRethrownStackAsSuppressed(ExceptionUtilRt.java:43)
		at com.intellij.util.ExceptionUtilRt.rethrowUnchecked(ExceptionUtilRt.java:16)
		at org.jetbrains.concurrency.AsyncPromise.blockingGet(AsyncPromise.kt:145)
		at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.executeSynchronously(NonBlockingReadActionImpl.java:531)
		... 12 more
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [Kernel@i8ku5b7ot1jmdp1puptq, Rete(abortOnError=false, commands=capacity=2147483647,data=[onReceive], reteState=kotlinx.coroutines.flow.StateFlowImpl@59e5ddf, dbSource=ReteDbSource(reteState=kotlinx.coroutines.flow.StateFlowImpl@59e5ddf)), DbSourceContextElement(kernel Kernel@i8ku5b7ot1jmdp1puptq), ComponentManager(ApplicationImpl@2145353539), com.intellij.codeWithMe.ClientIdContextElementPrecursor@55e5b429, CoroutineName(FileBasedIndex Vfs Event Processor), StandaloneCoroutine{Cancelled}@10bd382c, Dispatchers.IO.limitedParallelism(1)]

```

## System Information

 - Operating system: OSX 15.6.1
 - Strawberry version (if applicable):
strawberry-graphql-django = "^0.65.1"
strawberry-graphql = "^0.281.0"

## Additional Context

<img width="936" height="646" alt="Image" src="https://github.com/user-attachments/assets/a8715ea1-f11a-4259-8560-ff04a8b0306b" />
